# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Assam < Formula
  desc "Get a credential by AssumeRoleWithSAML for AWS CLI and SDK"
  homepage ""
  version "1.5.6"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/naotama2002-org/assam/releases/download/v1.5.6/assam_1.5.6_Darwin_arm64.tar.gz"
      sha256 "7fda92d53c2e04165b4b0d50ae04602e395f992e0c4b34147a4db39590bc9904"

      def install
        bin.install "assam"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/naotama2002-org/assam/releases/download/v1.5.6/assam_1.5.6_Darwin_x86_64.tar.gz"
      sha256 "50fb895868b5fe432e45dc2e65ae6cbbe0012bd1066e9233eeabade43790e9e2"

      def install
        bin.install "assam"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/naotama2002-org/assam/releases/download/v1.5.6/assam_1.5.6_Linux_x86_64.tar.gz"
      sha256 "9913ab82409ac6218f7b54fd0b395fc010e6c574f24decec76be520566f2792a"

      def install
        bin.install "assam"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/naotama2002-org/assam/releases/download/v1.5.6/assam_1.5.6_Linux_arm64.tar.gz"
      sha256 "44b6f49393cf689d25b00434f4f51fac7e59b26fc1704509889e8c0fb7797d42"

      def install
        bin.install "assam"
      end
    end
  end
end
