# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Assam < Formula
  desc "Get a credential by AssumeRoleWithSAML for AWS CLI and SDK"
  homepage ""
  version "1.5.4"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/naotama2002-org/assam/releases/download/v1.5.4/assam_1.5.4_Darwin_arm64.tar.gz"
      sha256 "568914ce62ad8732c2dbfe7a5161b09dc997aaaab2a439aaeb65ba25fbb02157"

      def install
        bin.install "assam"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/naotama2002-org/assam/releases/download/v1.5.4/assam_1.5.4_Darwin_x86_64.tar.gz"
      sha256 "5feb231037d268977d2914624c63c8a20aff0dc52dc050c6603adee52cef57f7"

      def install
        bin.install "assam"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/naotama2002-org/assam/releases/download/v1.5.4/assam_1.5.4_Linux_arm64.tar.gz"
      sha256 "f7bb0873eaa51f5348442f1eb2dbd1974e5d5b00ab5005fb6ebdcda247b477bf"

      def install
        bin.install "assam"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/naotama2002-org/assam/releases/download/v1.5.4/assam_1.5.4_Linux_x86_64.tar.gz"
      sha256 "d940b46c528420df7100ff35247e724b92330252328406397de14404e8b8a95a"

      def install
        bin.install "assam"
      end
    end
  end
end
